const foods = [
  {id:1,name:"Garden Margherita",category:"Pizza",price:249,type:"Veg",description:"Tomato, basil, mozzarella and a crisp golden crust.",image:"https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=700&q=80"},
  {id:2,name:"Smoky Paneer Pizza",category:"Pizza",price:329,type:"Veg",description:"Tandoori paneer, peppers, onion and smoky chipotle sauce.",image:"https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=700&q=80"},
  {id:3,name:"Classic Smash Burger",category:"Burger",price:219,type:"Non-Veg",description:"Juicy chicken patty, cheddar, lettuce and house sauce.",image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80"},
  {id:4,name:"Crispy Veggie Burger",category:"Burger",price:189,type:"Veg",description:"Crunchy veggie patty, pickles, tomato and creamy slaw.",image:"https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=700&q=80"},
  {id:5,name:"Butter Paneer Bowl",category:"Indian",price:259,type:"Veg",description:"Silky tomato gravy, paneer, rice and warm naan bites.",image:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=80"},
  {id:6,name:"Chicken Biryani",category:"Indian",price:299,type:"Non-Veg",description:"Fragrant basmati rice, tender chicken and aromatic spices.",image:"https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=700&q=80"},
  {id:7,name:"Chilli Garlic Noodles",category:"Chinese",price:199,type:"Veg",description:"Wok-tossed noodles with crunchy vegetables and sesame.",image:"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=700&q=80"},
  {id:8,name:"Mango Cheesecake",category:"Dessert",price:149,type:"Veg",description:"Creamy cheesecake topped with bright Alphonso mango.",image:"https://images.unsplash.com/photo-1547414368-ac947d00b91d?auto=format&fit=crop&w=700&q=80"}
];
const categories=["All","Pizza","Burger","Indian","Chinese","Dessert"], money=value=>`₹${value.toLocaleString("en-IN")}`, foodById=id=>foods.find(food=>food.id===id), getCart=()=>JSON.parse(localStorage.getItem("freshbite-cart")||"[]"), saveCart=cart=>localStorage.setItem("freshbite-cart",JSON.stringify(cart)), count=cart=>cart.reduce((sum,item)=>sum+item.quantity,0), subtotal=cart=>cart.reduce((sum,item)=>sum+foodById(item.id).price*item.quantity,0), delivery=cart=>subtotal(cart)>=499?0:39;
function updateCount(){const cartCount=count(getCart());document.querySelectorAll("[data-cart-count]").forEach(el=>el.textContent=cartCount);document.querySelectorAll(".cart-link").forEach(link=>{if(link.firstChild)link.firstChild.textContent="🛒 ";link.setAttribute("aria-label","Cart");link.title="Cart"});document.querySelectorAll(".brand-mark").forEach(mark=>mark.style.display="none");const cartActions=document.querySelector("#cartActions");if(cartActions){cartActions.hidden=cartCount===0;document.querySelector("#cartActionText").textContent=`${cartCount} ${cartCount===1?"item":"items"} in your cart`}}
function renderMenu(category="All"){const cart=getCart();document.querySelector("#foodGrid").innerHTML=(category==="All"?foods:foods.filter(food=>food.category===category)).map(food=>{const quantity=cart.find(item=>item.id===food.id)?.quantity||0;const action=quantity?`<div class="quantity"><button type="button" data-quantity="${food.id}" data-change="-1" aria-label="Decrease ${food.name}">−</button><span>${quantity}</span><button type="button" data-quantity="${food.id}" data-change="1" aria-label="Increase ${food.name}">+</button></div>`:`<button class="add-button" type="button" data-add="${food.id}">Add to cart</button>`;return`<article class="food-card"><img class="food-image" src="${food.image}" alt="${food.name}" loading="lazy"><div class="food-content"><div class="food-top"><h3 class="food-name">${food.name}</h3><span class="food-price">${money(food.price)}</span></div><p class="food-description">${food.description}</p><div class="food-bottom"><span class="diet ${food.type==="Non-Veg"?"nonveg":""}">${food.type}</span>${action}</div></div></article>`}).join("")}
function renderFilters(){document.querySelector("#filters").innerHTML=categories.map(category=>`<button class="filter ${category==="All"?"active":""}" type="button" data-category="${category}">${category}</button>`).join("")}
function renderCart(){const cart=getCart(), box=document.querySelector("#cartItems");document.querySelector("#cartItemLabel").textContent=`${count(cart)} ${count(cart)===1?"item":"items"}`;if(!cart.length){box.innerHTML='<div class="empty-cart">Your cart is empty.</div>';document.querySelector("#cartTotals").hidden=true;return}document.querySelector("#cartTotals").hidden=false;box.innerHTML=cart.map(item=>{const food=foodById(item.id);return`<div class="cart-item"><div><h4>${food.name}</h4><span class="cart-item-price">${money(food.price)} each</span></div><div class="cart-item-actions"><div class="quantity"><button type="button" data-quantity="${food.id}" data-change="-1">−</button><span>${item.quantity}</span><button type="button" data-quantity="${food.id}" data-change="1">+</button></div><button class="remove-button" type="button" data-remove="${food.id}">Remove</button></div></div>`}).join("");document.querySelector("#subtotal").textContent=money(subtotal(cart));document.querySelector("#deliveryFee").textContent=delivery(cart)?money(delivery(cart)):"Free";document.querySelector("#total").textContent=money(subtotal(cart)+delivery(cart))}
function changeQuantity(id,delta){const cart=getCart(),item=cart.find(entry=>entry.id===id);if(item)item.quantity+=delta;else if(delta>0)cart.push({id,quantity:delta});saveCart(cart.filter(entry=>entry.quantity>0));if(document.querySelector("#cartItems"))renderCart();if(document.querySelector("#foodGrid"))renderMenu(document.querySelector(".filter.active")?.dataset.category||"All");updateCount()}
function renderCheckout(){const cart=getCart();if(!cart.length){location.href="cart.html";return}document.querySelector("#checkoutSummary").innerHTML=cart.map(item=>{const food=foodById(item.id);return`<div class="summary-row"><span>${food.name} × ${item.quantity}</span><span>${money(food.price*item.quantity)}</span></div>`}).join("")+`<div class="summary-row"><span>Delivery fee</span><span>${delivery(cart)?money(delivery(cart)):"Free"}</span></div><div class="summary-total"><span>Total</span><span>${money(subtotal(cart)+delivery(cart))}</span></div>`}
function renderConfirmation(){const order=JSON.parse(localStorage.getItem("freshbite-last-order")||"null");if(!order){location.href="index.html";return}document.querySelector("#orderId").textContent=order.id;document.querySelector("#confirmationTotal").textContent=money(order.total);document.querySelector("#orderedItems").innerHTML=order.items.map(item=>{const food=foodById(item.id);return`<div class="ordered-item"><span>${food.name} × ${item.quantity}</span><strong>${money(food.price*item.quantity)}</strong></div>`}).join("")}
document.addEventListener("click",event=>{const category=event.target.closest("[data-category]");if(category){document.querySelectorAll(".filter").forEach(btn=>btn.classList.toggle("active",btn===category));renderMenu(category.dataset.category)}const add=event.target.closest("[data-add]");if(add)changeQuantity(Number(add.dataset.add),1);const quantity=event.target.closest("[data-quantity]");if(quantity)changeQuantity(Number(quantity.dataset.quantity),Number(quantity.dataset.change));const remove=event.target.closest("[data-remove]");if(remove){saveCart(getCart().filter(item=>item.id!==Number(remove.dataset.remove)));if(document.querySelector("#cartItems"))renderCart();if(document.querySelector("#foodGrid"))renderMenu(document.querySelector(".filter.active")?.dataset.category||"All");updateCount()}});
const page=document.body.dataset.page;updateCount();if(page==="home"){renderFilters();renderMenu()}if(page==="cart")renderCart();if(page==="checkout")renderCheckout();if(page==="confirmation")renderConfirmation();
const paymentInputs=document.querySelectorAll("input[name=payment]");const upiDetails=document.querySelector("#upiDetails"),cardDetails=document.querySelector("#cardDetails");function updatePaymentFields(){const selected=document.querySelector("input[name=payment]:checked")?.value;upiDetails.hidden=selected!=="UPI";cardDetails.hidden=selected!=="Card";document.querySelectorAll("#upiDetails input").forEach(input=>{input.required=selected==="UPI"});document.querySelectorAll("#cardDetails input").forEach(input=>{input.required=selected==="Card"})}paymentInputs.forEach(input=>input.addEventListener("change",updatePaymentFields));if(paymentInputs.length)updatePaymentFields();
const form=document.querySelector("#checkoutForm");if(form)form.addEventListener("submit",event=>{event.preventDefault();if(!form.checkValidity()){document.querySelector("#formError").classList.add("show");form.reportValidity();return}const cart=getCart();localStorage.setItem("freshbite-last-order",JSON.stringify({id:`FB${Date.now().toString().slice(-6)}`,items:cart,total:subtotal(cart)+delivery(cart)}));localStorage.removeItem("freshbite-cart");location.href="confirmation.html"});
